FROM ubuntu:latest
LABEL image="frontendstatic"
RUN apt update 
RUN apt install apache2 -y
RUN rm -rf /var/www/html/index.html
WORKDIR /var/www/html
RUN mv Vr-website.html /var/www/html/Vr-website.html
EXPOSE 80
CMD ["apachectl", "-D" ,"FOREGROUND"]