services:  #services syntax comples the creation of cont from img via docfile , assigns network , assigns volumes as well.
  nginxfrontendconone:
      build: .
      ports: 
          - '8080:80'
      network_mode: bridge
      container_name: setback
      volumes: 
         - ./my-httpd.conf:/usr/local/apache2/conf/httpd.conf
  nginxfrontendcontwo:
      build: . 
      #ports: - "81:81"
      network_mode: host
      volumes: 
         - ./my-httpd.conf:/usr/local/apache2/conf/httpd.conf
      container_name: backend 
volumes:   # will create a volume for you.
      myapp:
      myapp2:
networks:
  myappnetwork:





