
FROM ubuntu:latest
LABEL image="frontendstatic"
RUN apt update 
RUN apt install apache2 -y
RUN rm -rf /var/www/html/index.html
COPY test.html /var/www/html/
EXPOSE 80
CMD ["apachectl", "-D" ,"FOREGROUND"]