services: 
 swapnil's-container:
   container_name: swapnil
   build: /home/ubuntu/docker/docker compose
   port: 
    - '80-80'
   network_mode: default
   volume: 
      - myapp:/usr/share/nginx/html/

    gade'-container: 
     container_name: gade
     build: . /home/ubuntu/docker/docker compose
     ports: 
      - '81:81'
     network_mode: default
     volumes: 
       - myapp2:/usr/share/nginx/html/ 
     