services:  #services syntax comples the creation of cont from img via docfile , assigns network , assigns volumes as well.
  nginxfrontendconone:
      build: .
      ports: 
          - '81:81'
      network_mode: bridge
      container_name: frontnend
      volumes: 
         - myapp1:/usr/share/nginx/html/ 
  nginxfrontendcontwo:
      build: . 
      #ports: - "81:81"
      network_mode: host
      volumes: 
        - myapp2:/usr/share/nginx/html/ 
      container_name: frontnend2
#volumes:   # will create a volume for you.
      myapp:
      myapp2:
#networks:
 # myappnetwork:


